<a href="https://colab.research.google.com/github/mojtaba732/ML_Practice/blob/main/MissingDataHandling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
from io import StringIO
from sklearn.impute import SimpleImputer

In [3]:
csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [ ]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [ ]:
df.isnull().sum()
#This way, we can count the number of missing values per column

A    0
B    0
C    1
D    1
dtype: int64

In [ ]:
#Pandas DataFrame to NumPy Array
df.values

6.0

**Eliminating training examples or features with missing values**

In [ ]:
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

**The dropna method supports several additional parameters that can come in handy**

In [ ]:
# only drop rows where all columns are NaN
df.dropna(how='all')

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [4]:
# drop rows that have fewer than 4 real values
df.dropna(thresh=4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [5]:
# only drop rows where NaN appear in specific columns (here: 'C')
df.dropna(subset=['C'])

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

**Imputing missing values**

In [11]:
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [12]:
df.fillna(df.mean())

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0